CREATE DATABASE auth;
CREATE USER auth PASSWORD 'auth';
GRANT ALL PRIVILEGES ON DATABASE "auth" TO auth;

CREATE DATABASE mobile;
CREATE USER mobile PASSWORD 'mobile';
GRANT ALL PRIVILEGES ON DATABASE "mobile" TO mobile;

