spring:
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:9901/auth
    username: auth
    password: auth
app:
  resourceServers:
    - name: mobile-service
      accessTokenLiveTimeSec: 3600
      refreshTokenLiveTimeSec: 2592000
      clientId:  mobile-client-id
      clientSecret:  mobile-client-secret
      scopes:
        - read
        - wtite
        - mobile
      grantTypes:
        - password
        - authorization_code
        - refresh_token
        - client_credentials
    - name: mobile-service
      accessTokenLiveTimeSec: 3600
      refreshTokenLiveTimeSec: 2592000
      clientId:  web-client-id
      clientSecret:  web-client-secret
      scopes:
        - read
        - wtite
        - web
      grantTypes:
        - password
        - authorization_code
        - refresh_token
        - client_credentials

server:
  port: 8085
logging:
  level:
    #    org.springframework.security: DEBUG
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql: TRACE
    ru.f0xdev.bank.auth-service: DEBUG
